import { spawnSync } from 'node:child_process'
import { expect, it } from 'vitest'

it('does not allocate a captured function context in the ordinary runner step', () => {
  // A conditional callback can allocate its captured parameter context before the branch.
  // Inspect the actual V8 bytecode, not source spelling or noisy heap/timing thresholds.
  const probe = spawnSync(
    process.execPath,
    [
      '--print-bytecode',
      '--print-bytecode-filter=stepOnce',
      '--import',
      new URL('./loader.mjs', import.meta.url).href,
      '--input-type=module',
      '--eval',
      `
      import { createRunController } from './packages/core/src/runner.ts'
      import { createFakeTimers } from './packages/core/src/testing/fake-timers.ts'
      const timers = createFakeTimers(0)
      const controller = createRunController({
        needsRenderBatch: () => false,
        batch: operation => operation(),
        render: () => undefined,
        emit() {}, reportError() {}, setState() {},
        frameFor: pose => pose,
        timers,
      }, { poseCount: 6 })
      controller.play(0, 5)
      timers.advance(95)
      controller.dispose()
    `,
    ],
    { cwd: process.cwd(), encoding: 'utf8', timeout: 20000 },
  )
  expect(probe.status, probe.stderr || String(probe.error)).toBe(0)
  expect(probe.stdout).toContain('generated bytecode for function: stepOnce ')
  expect(probe.stdout).not.toMatch(/CreateFunctionContext\w*|CreateClosure/)
})
